# this file is used to run github actions in tthe pipeline

name: Test Execution

on : [push]

jobs : 
  cypress-execution:
      runs-on: ubuntu-latest

      steps:
      - name : Initialize node and Install NPM
        uses: actions/checkout@v4

      - name : Excecute Cypress Script
        uses : cypress-io/github-actions@v6
